name: MemoryGym
options:
  bundleIdPrefix: com.memorygym
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: ko

settings:
  DEVELOPMENT_TEAM: "9Q26686S8R"
  CODE_SIGN_STYLE: Automatic

targets:
  MemoryGym:
    type: application
    platform: iOS
    sources:
      - path: .
        includes:
          - "*.swift"
          - "Assets.xcassets"
          - "Preview Content"
        excludes:
          - "*.md"
          - "*.py"
          - "project.yml"
          - ".git"
          - ".vscode"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: MemoryGym
        CFBundleIdentifier: com.memorygym.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities:
          - armv7 