name: MemoryGym
options:
  bundleIdPrefix: com.memorygym
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: ko

settings:
  DEVELOPMENT_TEAM: "9Q26686S8R"
  CODE_SIGN_STYLE: Automatic

targets:
  MemoryGym:
    type: application
    platform: iOS
    sources:
      - path: .
        includes:
          - "MemoryGymApp.swift"
          - "AuthenticationManager.swift"
          - "LoginView.swift"
          - "ContentView.swift"
          - "Models/"
          - "Services/"
          - "Views/"
          - "Assets.xcassets"
          - "Preview Content"
          - "GoogleService-Info.plist"
          - "MemoryGym.entitlements"
        excludes:
          - "*.md"
          - "*.py"
          - "project.yml"
          - ".git"
          - ".vscode"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.memorygym.app
      INFOPLIST_FILE: Info.plist
      CODE_SIGN_ENTITLEMENTS: MemoryGym.entitlements 