name: MemoryGym
options:
  bundleIdPrefix: com.memorygym
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: ko

settings:
  DEVELOPMENT_TEAM: "9Q26686S8R"
  CODE_SIGN_STYLE: Automatic

targets:
  MemoryGym:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "**/*.md"
          - "Pods/**"
        includes:
          - "**/*.swift"
          - "Models/**"
          - "Services/**"
          - "Views/**"
          - "Data/**"
          - "MemoryGymApp.swift"
          - "AuthenticationManager.swift"
          - "LoginView.swift"
          - "ContentView.swift"
          - "Assets.xcassets"
          - "Preview Content"
          - "GoogleService-Info.plist"
          - "MemoryGym.entitlements"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.memorygym.app
      INFOPLIST_FILE: Info.plist
      CODE_SIGN_ENTITLEMENTS: MemoryGym.entitlements 